# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='birthday',
            field=models.CharField(max_length=20),
        ),
    ]
